package main

import (
    "os"
    "fmt"
    "io/ioutil"
    "path"
    "path/filepath"
    "strings"
)

const kCmdName = "merge_src"
const kCmdFullName = "Merge Source"
const kCmdVersion = "0.1"
const kSeparator = "// #######################################################\n"
const kCommentPrefix = "// ## "
const kHeaderMsg = "Generated by merge_src from the following files:\n"

/* A naive parser for quoted #includes. Can be tricked if the #include is inside a C++-style comment. */
func getIncPath(line string) string {
    tline := strings.TrimSpace(line)
    if !strings.HasPrefix(tline, "#include") {
        return ""
    }
    
    parts := strings.Split(tline, `"`)
    if len(parts) < 3 || strings.TrimSpace(parts[0]) != "#include" {
        return ""
    }
    
    return parts[1]
}

func normalizedPath(filePath string) (string, error) {
    r, err := filepath.Abs(filePath)
    if err != nil {
        return "", fmt.Errorf("filepath.Abs() failed: %v", err)
    }
    
    r = filepath.Clean(r)
    if _, err := os.Stat(r); err != nil {
        return "", fmt.Errorf("os.Stat(r) failed: %v", err)
    }
    
    return r, nil
}

/* Returns whether two paths refer to the same file */
func sameFile(path1, path2 string) bool {
    finfo1, err := os.Stat(path1)
    if err != nil {
        return false
    }
    
    finfo2, err := os.Stat(path2)
    if err != nil {
        return false
    }

    return os.SameFile(finfo1, finfo2)
}

/* Remove the extension from a file path */
func stripExt(filePath string) string {
    return filePath[0:len(filePath)-len(filepath.Ext(filePath))]
}

func findImplPath(filePath string) (string, error) {
    /* The list of file extensions that we look for */
    var kImplExts = [...]string{".c", ".m"}
    filePathNoExt := stripExt(filePath)
    for _, ext := range kImplExts {
        implPath, err := normalizedPath(filePathNoExt+ext)
        if err == nil && !sameFile(filePath, implPath) {
            return implPath, nil
        }
    }
    return "", fmt.Errorf("failed to find implementation for %v\n", filePath)
}

func replaceIncludes(filePath string, root bool, impl bool, history map[string]bool) (result string, paths []string, err error) {
    /* Check whether we've visited this file yet. If not, mark it in our history */
    filePath, err = normalizedPath(filePath)
    if err != nil {
        return "", []string{}, err
    }
    if history[filePath] {
        return "", []string{}, nil
    } else {
        history[filePath] = true
    }
    
    /* Change to the directory where the file is located */
    oldWd, err := os.Getwd()
    if err != nil {
        return "", []string{}, fmt.Errorf("os.Getwd() failed: %v", err)
    }
    
    err = os.Chdir(path.Dir(filePath))
    if err != nil {
        return "", []string{}, fmt.Errorf("os.Chdir() failed: %v", err)
    }
    defer func() {
        /* Revert back to our old working directory upon return */
        err2 := os.Chdir(oldWd)
        if err == nil && err2 != nil {
            err = err2
        }
    }()
    
    /* Read the entire file */
    b, err := ioutil.ReadFile(filePath)
    if err != nil {
        return "", []string{}, fmt.Errorf("ioutil.ReadFile() failed: %v", err)
    }
    
    lines := strings.Split(strings.TrimSpace(string(b)), "\n")
    result = kSeparator+kCommentPrefix+filepath.Base(filePath)+"\n"+kSeparator+"\n"
    paths = []string{filePath}
    for _, line := range lines {
        /* Ignore `#pragma once` lines */
        parts := strings.Split(strings.TrimSpace(line), ` `)
        if parts[0] == "#pragma" && parts[1] == "once" {
            continue
        }
        
        incPath := getIncPath(line)
        /* Avoid including the root file's header */
        if incPath != "" && (!root || !sameFile(stripExt(filePath)+".h", incPath)) {
            /* Insert the content of the included file */
            s, tmpPaths, err := replaceIncludes(incPath, false, impl, history)
            if err != nil {
                return "", []string{}, err
            }
            result += s
            paths = append(paths, tmpPaths...)
            
            /* Insert the content of related implementation files, if allowed */
            if impl {
                implPath, err := findImplPath(incPath)
                if err == nil {
                    /* Insert the content of the included file */
                    s, tmpPaths, err := replaceIncludes(implPath, false, impl, history)
                    if err != nil {
                        return "", []string{}, err
                    }
                    result += s
                    paths = append(paths, tmpPaths...)
                }
            }
        } else {
            /* Just a normal line of code so just append it to our output */
            result += line+"\n"
        }
    }
    
    return result, paths, nil
}

func mergeSrc(headerPath string, implPath string) (header string, impl string, err error) {
    headerPath, err = normalizedPath(headerPath)
    if err != nil {
        return "", "", fmt.Errorf("normalizedPath() failed: %v", err)
    }
    
    implPath, err = normalizedPath(implPath)
    if err != nil {
        return "", "", fmt.Errorf("normalizedPath() failed: %v", err)
    }

    history := map[string]bool{}
    
    /* Process the header */
    header, headerPaths, err := replaceIncludes(headerPath, true, false, history)
    if err != nil {
        fmt.Printf("%v\n", err)
        os.Exit(1)
    }
    
    /* Process the implementation */
    impl = ""
    s, _, err := replaceIncludes(implPath, true, true, history)
    if err != nil {
        fmt.Printf("%v\n", err)
        os.Exit(1)
    }
    impl += s
    
    /* Finally, append any remaining implementations for every header that we visited from the root header. */
    for _, headerPath := range headerPaths {
        implPath, err := findImplPath(headerPath)
        if err != nil {
            continue
        }
        
        s, _, err := replaceIncludes(implPath, true, true, history)
        if err != nil {
            fmt.Printf("%v\n", err)
            os.Exit(1)
        }
        impl += s
    }
    
    /* Prepend our prefix to the header */
    prefix := kSeparator+kCommentPrefix+kHeaderMsg
    for filePath, _ := range history {
        prefix += kCommentPrefix+"  "+filepath.Base(filePath)+"\n"
    }
    prefix += kSeparator+"\n"
    header = prefix+header
    
    return header, impl, nil
}

func main() {
	usage := fmt.Sprintf(`%v %v

Usage:
  %v src.h src.c output_dir
`, kCmdFullName, kCmdVersion, kCmdName)
    
    if len(os.Args) != 4 {
		fmt.Printf("%v", usage)
		os.Exit(1)
    }
    
    /* Get our input args */
    headerPath := os.Args[1]
    implPath := os.Args[2]
    outputDir := os.Args[3]
    
    /* Find the header file */
    headerPath, err := normalizedPath(headerPath)
    if err != nil {
        fmt.Printf("%v\n", err)
        os.Exit(1)
    }
    
    /* Find the implementation file */
    implPath, err = normalizedPath(implPath)
    if err != nil {
        fmt.Printf("%v\n", err)
        os.Exit(1)
    }
    
    /* Merge our sources! */
    header, impl, err := mergeSrc(headerPath, implPath)
    if err != nil {
        fmt.Printf("%v\n", err)
        os.Exit(1)
    }
    
    /* Create our output directory */
    os.MkdirAll(outputDir, 0777)
    
    /* Verify that we're not going to overwrite our input header file */
    outHeaderPath := filepath.Join(outputDir, filepath.Base(headerPath))
    if sameFile(headerPath, outHeaderPath) {
        fmt.Printf("Refusing to overwrite input file: %v\n", headerPath)
        os.Exit(1)
    }
    
    /* Verify that we're not going to overwrite our input implementation file */
    outImplPath := filepath.Join(outputDir, filepath.Base(implPath))
    if sameFile(implPath, outImplPath) {
        fmt.Printf("Refusing to overwrite input file: %v\n", implPath)
        os.Exit(1)
    }
    
    /* Write the output header file */
    const kPerm = 0644
    err = ioutil.WriteFile(outHeaderPath, []byte(header), kPerm)
    if err != nil {
        fmt.Printf("ioutil.WriteFile() failed: %v\n", err)
        os.Exit(1)
    }
    
    /* Write the output implementation file */
    err = ioutil.WriteFile(outImplPath, []byte(impl), kPerm)
    if err != nil {
        fmt.Printf("ioutil.WriteFile() failed: %v\n", err)
        os.Exit(1)
    }
    
    fmt.Printf("Wrote:\n  %v\n  %v\n", outHeaderPath, outImplPath)
}
